### PR TITLE
Prerelease changes

### PR DESCRIPTION
**Pull request by tsujan**
The release note will be as follows:

`qtxdg-tools` is separated from `libqtxdg`. It will be used by `xdg-utils` under an LXQt session, for controlling default applications and getting MIME types.

@stefonarch, would you please check the new `README.md`?

### CODE REVIEW

**Comment by stefonarch** [comment]
I'm quite  sleepy and copy/pasted a README too... https://github.com/lxqt/qtxdg-tools/pull/5, maybe you'll find something useful, although it's not my piece of cake.

`lxqt-build-tools` is already a dependency of libqtxdg so it's not really needed to list.

**Comment by tsujan** [comment]
@stefonarch 
Thanks! I'll do as you said.

**Comment by stefonarch** [comment]
Website is ready to update:

schermata-7 mag 10:46

**Comment by tsujan** [comment]
Done.

Will release it (alongside `libqtxdg` and `lxqt-session`) tomorrow.

**Comment by stefonarch** [comment]
Ok, here are the website articles, please recheck them:
https://github.com/lxqt/lxqt.github.io/compare/master...stefonarch:1.1.1_release?expand=1

[will change date to tomorrow]

**Comment by tsujan** [comment]
> please recheck them:

They seem OK to me. Thanks!

**Pull request merged**
