### PR TITLE
Adds find_package CMake stuff

### PR DESCRIPTION
**Pull request by luis-pereira**
It allows other projects to find if qtxdg-tools is present or not, via CMake.

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
GTM

**Comment by tsujan** [comment]
Added a commit for bumping `LXQTBT_MINIMUM_VERSION` to 0.11.0.

I'll set the other versions when making prerelease changes.

**Comment by tsujan** [comment]
Any objection to merging this and starting to prepare LXQt for Qt6?

**Comment by yan12125** [comment]
Go ahead!

**Comment by luis-pereira** [comment]
Go ahead.


--
Cumprimentos
Regards

A sábado, 30/04/2022, 18:30, Chih-Hsuan Yen ***@***.***>
escreveu:

**Pull request merged**
